THREEB = {
    'BB': {
        'vs_BTN': {
            "A2s": 1.0,
            "A3s": 1.0,
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AJs": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
        },
        'vs_CO': {
            "A3s": 1.0,
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
        },
        'vs_HJ': {
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
        },
        'vs_SB': {
            "97s": 1.0,
            "A2s": 1.0,
            "A3s": 1.0,
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AJs": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "ATs": 1.0,
            "J9s": 1.0,
            "JJ": 1.0,
            "K9s": 1.0,
            "KK": 1.0,
            "Q9s": 1.0,
            "QQ": 1.0,
            "T8s": 1.0,
            "TT": 1.0,
        },
        'vs_UTG': {
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "KK": 1.0,
        },
    },

    'BTN': {
        'vs_CO': {
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
        },
        'vs_HJ': {
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
        },
        'vs_UTG': {
            "AA": 1.0,
            "AKs": 1.0,
            "KK": 1.0,
        },
    },

    'CO': {
        'vs_HJ': {
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
        },
        'vs_UTG': {
            "AA": 1.0,
            "AKs": 1.0,
            "KK": 1.0,
        },
    },

    'HJ': {
        'vs_UTG': {
            "AA": 1.0,
            "AKs": 1.0,
            "KK": 1.0,
        },
    },

    'SB': {
        'vs_BTN': {
            "53s": 1.0,
            "64s": 1.0,
            "75s": 1.0,
            "86s": 1.0,
            "97s": 1.0,
            "99": 1.0,
            "A2s": 1.0,
            "A3s": 1.0,
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AJs": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQo": 1.0,
            "AQs": 1.0,
            "ATs": 1.0,
            "J9s": 1.0,
            "JJ": 1.0,
            "K8s": 1.0,
            "K9s": 1.0,
            "KK": 1.0,
            "KQs": 1.0,
            "Q9s": 1.0,
            "QQ": 1.0,
            "T8s": 1.0,
            "TT": 1.0,
        },
        'vs_CO': {
            "A3s": 1.0,
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "JJ": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
            "TT": 1.0,
            "AJs": 0.5,
            "AQo": 0.5,
            "J9s": 0.5,
            "K9s": 0.5,
            "Q9s": 0.5,
        },
        'vs_HJ': {
            "A4s": 1.0,
            "A5s": 1.0,
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "AQs": 1.0,
            "JJ": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
            "AJs": 0.5,
            "TT": 0.5,
        },
        'vs_UTG': {
            "AA": 1.0,
            "AKo": 1.0,
            "AKs": 1.0,
            "KK": 1.0,
            "QQ": 1.0,
            "A5s": 0.5,
            "AQs": 0.5,
            "JJ": 0.5,
        },
    },

}
THREEB['BB']['vs_MP'] = THREEB['BB']['vs_HJ']
THREEB['BB']['vs_EP'] = THREEB['BB']['vs_UTG']
THREEB['SB']['vs_MP'] = THREEB['SB']['vs_HJ']
THREEB['SB']['vs_EP'] = THREEB['SB']['vs_UTG']
THREEB['BTN']['vs_MP'] = THREEB['BTN']['vs_HJ']
THREEB['BTN']['vs_EP'] = THREEB['BTN']['vs_UTG']
THREEB['CO']['vs_MP'] = THREEB['CO']['vs_HJ']
THREEB['CO']['vs_EP'] = THREEB['CO']['vs_UTG']