# HU-2..HU-6 anchors extracted from design/hu_reference_set/
# Excludes HU-6.5 (already adjudicated CALL by owner; PR #338)
# Generated 2026-05-10

HU2_ANCHORS = [
    {
        "ref_id": "HU-2.1",
        "marker": "CANONICAL",
        "hero_cards": "AhQh",
        "board_flop": "Kd7h4h",
        "street": "flop",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "Draws (nut FD + two overcards)",
        "axis": "IP semi-bluff c-bet with nut FD on K-high two-tone",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop Kd7h4h two-tone hearts. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-2.2",
        "marker": "CANONICAL",
        "hero_cards": "Td9d",
        "board_flop": "8s6c2d",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 5.5,
        "facing_bet": True,
        "to_call_bb": 3.6,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "Draws (OESD + backdoor FD)",
        "axis": "OOP pot-odds call with OESD vs 66% c-bet",
        "action_summary": "BTN opens 2.5bb, SB folds, BB (hero) defends call. Flop 8s6c2d rainbow. BB checks, BTN bets 3.6bb (66% pot). Hero acts.",
    },
    {
        "ref_id": "HU-2.3",
        "marker": "CLOSE",
        "hero_cards": "Js9s",
        "board_flop": "Qs7s3d",
        "board_turn": "Qs7s3d2c",
        "street": "turn",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 11,
        "facing_bet": True,
        "to_call_bb": 8.25,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "Draws (bare nut FD + gutshot)",
        "axis": "OOP nut-FD facing turn 75% barrel; fold/call/check-raise threshold",
        "action_summary": "BTN opens 2.5bb, SB folds, BB (hero) calls. Flop Qs7s3d. BB checks, BTN bets 1.4bb (25%), BB calls. Turn 2c brick. BB checks, BTN bets 8.25bb (75% pot). Hero acts.",
    },
    {
        "ref_id": "HU-2.4",
        "marker": "CLOSE",
        "hero_cards": "6c5c",
        "board_flop": "8c7d4h",
        "street": "flop",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 14.85,
        "facing_bet": True,
        "to_call_bb": 9.9,
        "effective_stack_bb": 60,
        "opener": "BTN",
        "bettor": "BB",
        "composition": "Draws (combo: OESD + backdoor FD)",
        "axis": "IP combo-draw facing OOP check-raise; fold/call/jam at compressed SPR",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop 8c7d4h rainbow. BB checks, BTN bets 3.63bb (66%). BB check-raises to 9.9bb (~3x). Hero acts.",
    },
    {
        "ref_id": "HU-2.5",
        "marker": "CLOSE",
        "hero_cards": "Ad5d",
        "board_flop": "Jh8d3c",
        "board_turn": "Jh8d3c2d",
        "street": "turn",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "Draws (turned nut FD + gutshot, A-overcard)",
        "axis": "IP checked-to turn semi-bluff sizing with turned FD + A-blocker",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop Jh8d3c. BB checks, BTN checks back. Turn 2d completes hero's diamond FD. BB checks. Hero acts.",
    },
]

HU3_ANCHORS = [
    {
        "ref_id": "HU-3.1",
        "marker": "CANONICAL",
        "hero_cards": "7c6h",
        "board_flop": "AhKd4s",
        "street": "flop",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "air (pure-air, no backdoors)",
        "axis": "Range-c-bet bluff on dry A-high BTN-favoured board",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop AhKd4s rainbow. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-3.2",
        "marker": "CANONICAL",
        "hero_cards": "4d3d",
        "board_flop": "QcJh9s",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 5.5,
        "facing_bet": True,
        "to_call_bb": 3.6,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "air (pure-air, no realisable equity)",
        "axis": "Clear OOP check-fold on connected broadway flop facing 66% c-bet",
        "action_summary": "BTN opens 2.5bb, SB folds, BB (hero) calls. Flop QcJh9s rainbow connected broadway. BB checks, BTN bets 3.6bb (66% pot). Hero acts.",
    },
    {
        "ref_id": "HU-3.3",
        "marker": "CLOSE",
        "hero_cards": "KsQs",
        "board_flop": "8h6h5c",
        "board_turn": "8h6h5c2d",
        "street": "turn",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "air (two-overcard, subordinate overcard equity)",
        "axis": "IP checked-to turn float vs delayed-stab with two overcards",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop 8h6h5c two-tone. BB checks, BTN checks back. Turn 2d brick. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-3.4",
        "marker": "CLOSE",
        "hero_cards": "Ts8h",
        "board_flop": "7d7c3h",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 5.5,
        "facing_bet": True,
        "to_call_bb": 1.4,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "air (one-overcard + backdoor straight)",
        "axis": "OOP check-raise bluff vs check-call vs check-fold on paired board facing 25% c-bet",
        "action_summary": "BTN opens 2.5bb, SB folds, BB (hero) calls. Flop 7d7c3h paired rainbow. BB checks, BTN bets 1.4bb (25% pot). Hero acts.",
    },
    {
        "ref_id": "HU-3.5",
        "marker": "CLOSE",
        "hero_cards": "Ac4c",
        "board_flop": "Kh9d6s",
        "board_turn": "Kh9d6s5h",
        "board_river": "Kh9d6s5h2c",
        "street": "river",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 12,
        "facing_bet": True,
        "to_call_bb": 4,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BB",
        "composition": "air (busted, A-blocker)",
        "axis": "Busted-air give-up vs bluff-catch vs raise facing river block-lead with A-blocker",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop Kh9d6s. BB checks, BTN bets 1.4bb (25%), BB calls. Turn 5h. BB checks, BTN checks back. River 2c. BB leads 4bb (33% pot). Hero acts.",
    },
]

HU4_ANCHORS = [
    {
        "ref_id": "HU-4.1",
        "marker": "CANONICAL",
        "hero_cards": "JsJh",
        "board_flop": "Kd7h2c",
        "street": "flop",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "TP+ (overpair to 7-2; second pair to king)",
        "axis": "PFA small range c-bet with medium overpair on dry K-high",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop Kd7h2c rainbow. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-4.2",
        "marker": "CANONICAL",
        "hero_cards": "4h4c",
        "board_flop": "KhQh9h",
        "street": "flop",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "air (small underpair, dominated on monotone broadway)",
        "axis": "PFA check-back with bottom-of-range on BB-favoured monotone broadway",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop KhQh9h monotone hearts. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-4.3",
        "marker": "CLOSE",
        "hero_cards": "KsTs",
        "board_flop": "Td7d5s",
        "street": "flop",
        "hero_pos": "SB",
        "villain_pos": "BB",
        "pot_bb": 6,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "SB",
        "bettor": None,
        "composition": "TP+ (TPGK on T-high two-tone)",
        "axis": "SB c-bet sizing dilemma 25% vs 66% vs check on wet two-tone",
        "action_summary": "SB (hero) opens 3bb, BB calls. Flop Td7d5s two-tone diamonds. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-4.4",
        "marker": "CLOSE",
        "hero_cards": "QhJh",
        "board_flop": "9h8h2c",
        "street": "flop",
        "hero_pos": "SB",
        "villain_pos": "BB",
        "pot_bb": 6,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "SB",
        "bettor": None,
        "composition": "Draws (combo: FD + gutshot + two overcards)",
        "axis": "SB polar 66% vs 25% vs check with combo draw on wet two-tone",
        "action_summary": "SB (hero) opens 3bb, BB calls. Flop 9h8h2c two-tone hearts. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-4.5",
        "marker": "CLOSE",
        "hero_cards": "AhJc",
        "board_flop": "Tc7c3s",
        "board_turn": "Tc7c3s5d",
        "street": "turn",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "air (two-overcard + backdoor)",
        "axis": "IP delayed c-bet sizing on brick turn after flop check-back",
        "action_summary": "BTN (hero) opens 2.5bb, SB folds, BB calls. Flop Tc7c3s two-tone clubs. BB checks, BTN checks back. Turn 5d brick. BB checks. Hero acts.",
    },
]

HU5_ANCHORS = [
    {
        "ref_id": "HU-5.1",
        "marker": "CANONICAL",
        "hero_cards": "7d7s",
        "board_flop": "Th7c4h",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 7,
        "facing_bet": True,
        "to_call_bb": 4.6,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "TP+ (flopped middle set)",
        "axis": "OOP check-raise with flopped set on wet two-tone vs 66% c-bet",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop Th7c4h two-tone hearts. BB checks, BTN bets 4.6bb (66% pot). Hero acts.",
    },
    {
        "ref_id": "HU-5.2",
        "marker": "CANONICAL",
        "hero_cards": "7h6h",
        "board_flop": "7c6s4d",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "TP+ (flopped top two-pair)",
        "axis": "OOP donk-lead with two-pair on BB-favoured low-connected texture",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop 7c6s4d rainbow low-connected. BB acts first OOP. Hero acts.",
    },
    {
        "ref_id": "HU-5.3",
        "marker": "CLOSE",
        "hero_cards": "QdTh",
        "board_flop": "Qh8s5c",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 6.5,
        "facing_bet": True,
        "to_call_bb": 1.6,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "TP+ (top pair medium kicker)",
        "axis": "OOP check-call vs check-raise vs lead-turn with TP medium kicker facing 25% c-bet",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop Qh8s5c. BB checks, BTN bets 1.6bb (25% pot). Hero acts.",
    },
    {
        "ref_id": "HU-5.4",
        "marker": "CLOSE",
        "hero_cards": "Th8h",
        "board_flop": "9h7c2h",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "Draws (combo: OESD + second-nut FD)",
        "axis": "OOP donk-lead vs check-call vs check-raise with combo draw on wet two-tone",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop 9h7c2h two-tone hearts. BB acts first OOP. Hero acts.",
    },
    {
        "ref_id": "HU-5.5",
        "marker": "CLOSE",
        "hero_cards": "KsJc",
        "board_flop": "8h6d5h",
        "street": "flop",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 5.5,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "air (two-overcard + backdoor straight)",
        "axis": "OOP donk vs check-fold vs check-call with overcard-air on BB-favoured two-tone-connected",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop 8h6d5h two-tone hearts low-connected. BB acts first OOP. Hero acts.",
    },
]

HU6_ANCHORS = [
    # 4 entries; HU-6.5 excluded (already adjudicated CALL by owner; PR #338)
    {
        "ref_id": "HU-6.1",
        "marker": "CANONICAL",
        "hero_cards": "KhKs",
        "board_flop": "Kc7s4h",
        "board_turn": "Kc7s4h2c",
        "board_river": "Kc7s4h2cKd",
        "street": "river",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 13.7,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "TP+ (quad kings — absolute nuts)",
        "axis": "Nutted river 150% overbet for max value on paired dry runout",
        "action_summary": "BTN (hero) opens 2.5bb, BB calls. Flop Kc7s4h. BB checks, BTN bets 1.4bb (25%), BB calls. Turn 2c. BB checks, BTN bets 2.7bb (33%), BB calls. River Kd pairs the board for quads. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-6.2",
        "marker": "CANONICAL",
        "hero_cards": "8d8c",
        "board_flop": "Jh9h6h",
        "board_turn": "Jh9h6hTh",
        "board_river": "Jh9h6hThQd",
        "street": "river",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 13.7,
        "facing_bet": True,
        "to_call_bb": 20.6,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "air (busted underpair, no showdown value)",
        "axis": "Clear fold to 150% river overbet on completed-flush-and-straight runout",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop Jh9h6h monotone. BB checks, BTN bets 1.4bb (25%), BB calls. Turn Th. BB checks, BTN bets 2.7bb (33%), BB calls. River Qd. BTN bets 20.6bb (150% pot overbet). Hero acts.",
    },
    {
        "ref_id": "HU-6.3",
        "marker": "CLOSE",
        "hero_cards": "AsTs",
        "board_flop": "Tc7d3c",
        "board_turn": "Tc7d3c5h",
        "board_river": "Tc7d3c5h2s",
        "street": "river",
        "hero_pos": "BTN",
        "villain_pos": "BB",
        "pot_bb": 13.7,
        "facing_bet": False,
        "to_call_bb": 0,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": None,
        "composition": "TP+ (TPTK on dry-disconnected runout)",
        "axis": "River value-bet sizing tier 33% vs 75% vs 150% with TPTK",
        "action_summary": "BTN (hero) opens 2.5bb, BB calls. Flop Tc7d3c. BB checks, BTN bets 1.4bb (25%), BB calls. Turn 5h. BB checks, BTN bets 2.7bb (33%), BB calls. River 2s. BB checks. Hero acts.",
    },
    {
        "ref_id": "HU-6.4",
        "marker": "CLOSE",
        "hero_cards": "AcQh",
        "board_flop": "Qs9c4s",
        "board_turn": "Qs9c4s7c",
        "board_river": "Qs9c4s7c2h",
        "street": "river",
        "hero_pos": "BB",
        "villain_pos": "BTN",
        "pot_bb": 20.7,
        "facing_bet": True,
        "to_call_bb": 15.5,
        "effective_stack_bb": 100,
        "opener": "BTN",
        "bettor": "BTN",
        "composition": "TP+ (TPTK on busted-FD runout)",
        "axis": "Bluff-catch fold/call threshold facing 75% river triple-barrel on busted-FD",
        "action_summary": "BTN opens 2.5bb, BB (hero) calls. Flop Qs9c4s two-tone spades. BB checks, BTN bets 1.4bb (25%), BB calls. Turn 7c. BB checks, BTN bets 6.2bb (75%), BB calls. River 2h brick (FD busted). BTN bets 15.5bb (75% pot). Hero acts.",
    },
]

ALL_HU2_HU6_ANCHORS = HU2_ANCHORS + HU3_ANCHORS + HU4_ANCHORS + HU5_ANCHORS + HU6_ANCHORS
# Total: 24 anchors (5+5+5+5+4); HU-6.5 excluded
