"""Tests for action_string as a mandatory pipeline field.

Phase 0 requirement: every situation must carry a validated action_string
from factory through labelling. These tests verify:
1. _build_action_string() produces correct strings
2. SituationSpec.action_string is auto-generated by build_situation()
3. Pre-supplied action_strings are preserved
4. Invalid action_strings raise ValueError
5. label_situation() rejects records without action_string
"""
import json
import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from situation_factory import (
    _build_action_string,
    SituationSpec,
    build_situation,
)


# ── _build_action_string tests ──────────────────────────────────────


class TestBuildActionString:

    def test_no_prior_actions(self):
        """Hero first to act — string is just 'BTN ???'."""
        result = _build_action_string([], 'flop', 'BTN')
        assert result == 'BTN ???'

    def test_hero_after_checks(self):
        """Hero acts after two checks."""
        history = [
            ('flop', 'BB', 'check'),
            ('flop', 'CO', 'check'),
        ]
        result = _build_action_string(history, 'flop', 'BTN')
        assert result == 'BB check, CO check, BTN ???'

    def test_hero_faces_bet(self):
        """Hero faces a bet after a check."""
        history = [
            ('flop', 'BB', 'check'),
            ('flop', 'CO', 'bet'),
        ]
        result = _build_action_string(history, 'flop', 'BTN')
        assert result == 'BB check, CO bet, BTN ???'

    def test_cross_street_filtered(self):
        """Only current street actions appear in the string."""
        history = [
            ('preflop', 'CO', 'raise'),
            ('preflop', 'BB', 'call'),
            ('flop', 'BB', 'check'),
            ('flop', 'CO', 'bet'),
        ]
        result = _build_action_string(history, 'flop', 'BTN')
        assert result == 'BB check, CO bet, BTN ???'

    def test_hero_faces_bet_and_call(self):
        """Hero faces a bet with a caller in between."""
        history = [
            ('flop', 'BB', 'check'),
            ('flop', 'CO', 'bet'),
            ('flop', 'BTN', 'call'),
        ]
        result = _build_action_string(history, 'flop', 'BB')
        assert result == 'BB check, CO bet, BTN call, BB ???'

    def test_positions_uppercased(self):
        """Positions are uppercased even if input is lowercase."""
        history = [('flop', 'bb', 'check')]
        result = _build_action_string(history, 'flop', 'co')
        assert result == 'BB check, CO ???'

    def test_actions_lowercased(self):
        """Actions are lowercased even if input is mixed case."""
        history = [('flop', 'BB', 'Check')]
        result = _build_action_string(history, 'flop', 'CO')
        assert result == 'BB check, CO ???'


# ── SituationSpec + build_situation tests ────────────────────────────


def _make_valid_spec(**overrides):
    """Create a minimal valid SituationSpec for testing."""
    defaults = dict(
        hero_cards=['Ah', 'Kd'],
        board_cards=['Jh', '8c', '2s'],
        hero_pos='BTN',
        villain_positions=['BB', 'CO'],
        pot=90.0,
        to_call=0.0,
        street='flop',
        action_history=[
            ('flop', 'BB', 'check'),
            ('flop', 'CO', 'check'),
        ],
        opener_position='CO',
    )
    defaults.update(overrides)
    return SituationSpec(**defaults)


class TestBuildSituationActionString:

    def test_auto_generated(self):
        """action_string is auto-generated when not pre-supplied."""
        spec = _make_valid_spec()
        assert spec.action_string is None
        build_situation(spec)
        assert spec.action_string is not None
        assert spec.action_string.endswith('BTN ???')

    def test_pre_supplied_preserved(self):
        """Pre-supplied action_string is not overwritten."""
        spec = _make_valid_spec(
            action_string='BB check, CO check, BTN ???'
        )
        build_situation(spec)
        assert spec.action_string == 'BB check, CO check, BTN ???'

    def test_invalid_pre_supplied_raises(self):
        """Invalid pre-supplied action_string raises ValueError."""
        # BTN calls without a bet live — illegal
        spec = _make_valid_spec(
            action_string='BB check, CO check, BTN call 45, BB ???'
        )
        # Override hero_pos to BB so the ??? is for BB
        spec.hero_pos = 'BB'
        with pytest.raises(ValueError, match='Invalid action_string'):
            build_situation(spec)

    def test_hero_first_to_act(self):
        """When hero is first to act, action_string is just 'HERO ???'."""
        spec = _make_valid_spec(
            hero_pos='BB',
            action_history=[],
        )
        build_situation(spec)
        assert spec.action_string == 'BB ???'


# ── JSONL roundtrip test ─────────────────────────────────────────────


class TestJsonlRoundtrip:

    def test_action_string_survives_json(self):
        """action_string survives JSON serialization."""
        original = {
            'situation_id': 'test_001',
            'action_string': 'BB check, CO bet 45, BTN ???',
            'feat_dict': {'raw_equity': 0.5},
        }
        serialized = json.dumps(original)
        restored = json.loads(serialized)
        assert restored['action_string'] == original['action_string']


# ── label_situation guard test ───────────────────────────────────────


class TestLabelSituationGuard:

    def test_missing_action_string_raises(self):
        """label_situation() rejects records without action_string."""
        from label_3way_situations import label_situation
        with pytest.raises(ValueError, match='missing action_string'):
            label_situation({'situation_id': 'test_no_as'})

    def test_empty_action_string_raises(self):
        """label_situation() rejects records with empty action_string."""
        from label_3way_situations import label_situation
        with pytest.raises(ValueError, match='missing action_string'):
            label_situation({
                'situation_id': 'test_empty_as',
                'action_string': '',
            })
